import { ArrowLeft, ArrowUpRight, CalendarDays, CheckCheck, LockKeyhole, MapPin, ShieldCheck, Wallet } from 'lucide-react-native';
import { useEffect, useState } from 'react';
import { Linking, ScrollView, Text, TextInput, View } from 'react-native';
import { Avatar, Badge, Button, Copy, EmptyState, Heading, Logo, Notice, Panel, Sheet, SOSButton, Timeline } from '../components/ui';
import { professionals } from '../data/demo';
import { canViewJob, money, statusLabels } from '../domain/marketplace';
import { errorMessage, requireSupabase } from '../lib/supabase';
import { useAuth } from '../stores/auth';
import { useBookings } from '../stores/bookings';

export function ActiveJob({ jobId, onBack }: { jobId: string; onBack: () => void }) {
  const { profile, mode } = useAuth();
  const { demoJobs, liveJobs, startCode, transition } = useBookings();
  const demo = mode === 'demo';
  const job = (demo ? demoJobs : liveJobs).find(item => item.id === jobId);
  const [code, setCode] = useState('');
  const [entered, setEntered] = useState('');
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const [confirm, setConfirm] = useState<'complete' | 'cancel' | null>(null);
  const customer = profile?.role === 'customer';
  useEffect(() => {
    let alive = true;
    setCode('');
    if (profile && customer && job && ['requested', 'accepted'].includes(job.status)) startCode(job.id, profile, demo).then(value => { if (alive) setCode(value); }).catch(cause => { if (alive) setError(errorMessage(cause)); });
    return () => { alive = false; };
  }, [job, customer, profile, demo, startCode]);
  if (!profile || !job || !canViewJob(job, profile)) return <View className="flex-1 justify-center bg-canvas p-6"><EmptyState title="Booking unavailable" description="This booking does not exist or is not assigned to your account." action={<Button label="Back to overview" onPress={onBack} />} /></View>;
  const active = !['completed', 'cancelled'].includes(job.status);
  const runAction = async (action: 'accept' | 'start' | 'complete' | 'cancel') => {
    setBusy(true); setError(null);
    try { await transition(job.id, action, profile, demo, entered); setEntered(''); setConfirm(null); } catch (cause) { setError(errorMessage(cause)); } finally { setBusy(false); }
  };
  const recordSOS = async () => { if (!demo) { const { error: failure } = await requireSupabase().from('safety_alerts').insert({ job_id: job.id, user_id: profile.id }); if (failure) throw failure; } };
  return <View className="flex-1 bg-canvas"><View className="flex-row items-center justify-between border-b border-line bg-white px-5 py-4 md:px-10"><Logo /><Button label="Overview" variant="ghost" icon={ArrowLeft} onPress={onBack} /></View><ScrollView keyboardShouldPersistTaps="handled" contentContainerClassName="px-5 py-8 md:px-10"><View className="mx-auto w-full max-w-[1000px] gap-6"><View className="flex-row flex-wrap items-center justify-between gap-3"><View className="gap-2"><Copy className="text-xs text-muted">YOUR BOOKING / {job.id}</Copy><Heading className="text-[30px] leading-10">{job.title}</Heading></View><Badge label={statusLabels[job.status]} tone={job.status === 'accepted' ? 'amber' : 'green'} /></View>
    <View className="flex-col gap-6 md:flex-row"><View className="flex-1 gap-5"><Panel className="gap-5 p-6"><View className="flex-row items-center gap-4"><Avatar large name={customer ? job.workerName : job.customerName} uri={customer ? professionals.find(person => person.id === job.workerId)?.image : undefined} /><View className="gap-1"><Heading className="text-xl">{customer ? job.workerName : job.customerName}</Heading><Copy className="text-xs text-muted">{customer ? `${job.category} professional` : 'Your customer'}</Copy>{customer && <Badge label={demo ? 'Demo verified' : 'Identity verified'} icon />}</View></View><View className="gap-4 border-t border-line pt-5"><View className="flex-row items-start gap-3"><MapPin size={18} color="#7A8981" /><Copy className="flex-1">{job.address}</Copy></View><View className="flex-row items-center gap-3"><CalendarDays size={18} color="#7A8981" /><Copy>{new Date(job.scheduledAt).toLocaleString('en-IN', { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' })}</Copy></View><Copy className="text-muted">{job.description || 'No additional details provided.'}</Copy><Button label="Open directions" variant="secondary" icon={ArrowUpRight} onPress={() => { void Linking.openURL(`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(job.address)}`).catch(() => setError('Unable to open maps. Please use the address above.')); }} /></View></Panel>
      {active && <View className="gap-4 rounded-lg border border-[#CDDCD0] bg-mint p-6"><View className="flex-row items-center gap-2"><LockKeyhole size={21} color="#287454" /><Heading className="text-lg">{job.status === 'in_progress' ? 'Work is underway' : customer ? 'Your Secure Start Code' : 'Secure job start'}</Heading></View>{job.status === 'in_progress' ? <><Copy className="text-sm text-primary">The start code was confirmed. {customer ? 'Confirm completion when you are happy with the work.' : 'The customer will confirm completion when the job is done.'}</Copy>{customer && <Button label="Confirm completion" icon={CheckCheck} onPress={() => setConfirm('complete')} />}</> : customer ? <><Copy className="text-[13px] text-muted">Share this code only when your professional arrives and you are ready for work to begin.</Copy><View testID="start-code" accessibilityLabel={`Secure Start Code ${code}`} className="flex-row justify-center gap-3 py-3">{(code || '----').split('').map((digit, index) => <View key={index} className="h-[72px] w-[56px] items-center justify-center rounded-lg border border-[#CDDCD0] bg-white"><Text className="font-displaybold text-[34px] text-primary">{digit}</Text></View>)}</View><View className="flex-row items-center justify-center gap-2"><ShieldCheck size={14} color="#287454" /><Copy className="text-xs text-primary">Work stays locked until your code is confirmed.</Copy></View></> : job.status === 'requested' ? <><Copy className="text-[13px] text-muted">Review this request before accepting. You will need the customer&apos;s code to begin work.</Copy><Button label="Accept this job" loading={busy} onPress={() => void runAction('accept')} /></> : <><Copy className="text-[13px] text-muted">Ask the customer for their four-digit Secure Start Code when you arrive.</Copy><TextInput testID="worker-start-code" accessibilityLabel="Customer Secure Start Code" placeholder="0000" placeholderTextColor="#AAB9AE" value={entered} onChangeText={value => setEntered(value.replace(/\D/g, '').slice(0, 8))} maxLength={8} keyboardType="number-pad" autoComplete="off" className="h-[72px] rounded-lg border border-[#CDDCD0] bg-white px-5 text-center font-displaybold text-[32px] text-primary" /><Button label="Verify code & start job" icon={LockKeyhole} disabled={entered.trim().length === 0} loading={busy} onPress={() => void runAction('start')} /></>}</View>}
      {!active && <Notice message={job.status === 'completed' ? `This job is complete. ${demo ? 'The demo payment was released.' : 'The payment release has been queued for processing.'}` : 'This booking was cancelled.'} kind="success" />}<Notice message={error} />
    </View><View className="w-full gap-5 md:w-[300px]"><Panel className="gap-5 p-6"><Heading className="text-lg">Booking timeline</Heading><Timeline job={job} /></Panel><Panel className="gap-4 p-6"><View className="flex-row items-center gap-2"><Wallet size={19} color="#287454" /><Heading className="text-lg">Payment summary</Heading></View><View className="flex-row justify-between"><Copy className="text-muted">Service estimate</Copy><Copy className="font-semibold">{money(job.amount)}</Copy></View><View className="border-t border-line pt-4"><Badge label={demo ? `Demo escrow · ${job.escrowStatus.replace('demo_', '')}` : `Escrow · ${job.escrowStatus}`} tone={job.escrowStatus === 'unfunded' ? 'amber' : 'green'} /></View><Copy className="text-xs text-muted">{demo ? 'Simulation only. No money is collected or transferred.' : job.escrowStatus === 'unfunded' ? 'Payment is not funded. Starting work is blocked until the payment provider confirms funding.' : 'Payment release is processed after the customer confirms completion.'}</Copy></Panel>{customer && ['requested', 'accepted'].includes(job.status) && <Button label="Cancel booking" variant="ghost" onPress={() => setConfirm('cancel')} />}</View></View>
  </View></ScrollView>
    {active && <View className="border-t border-line bg-white px-5 py-3"><View className="mx-auto w-full max-w-[1000px] flex-row items-center justify-between gap-3"><View className="hidden flex-1 md:flex"><Copy className="text-xs text-muted">Your safety always comes first.</Copy></View><View className="flex-1 md:max-w-[260px]"><SOSButton jobId={job.id} demo={demo} onRecord={recordSOS} /></View></View></View>}
    <Sheet visible={confirm !== null} title={confirm === 'complete' ? 'Everything looking good?' : 'Cancel this booking?'} onClose={() => setConfirm(null)}><Copy>{confirm === 'complete' ? `Confirm that the work is complete. This authorizes ${demo ? 'a simulated' : 'the'} payment release of ${money(job.amount)} to ${job.workerName}.` : 'This action cancels the booking before work starts. Any funded payment will be queued for a refund.'}</Copy><Notice message={error} /><Button label={confirm === 'complete' ? 'Confirm & release payment' : 'Yes, cancel booking'} loading={busy} variant={confirm === 'cancel' ? 'danger' : 'primary'} onPress={() => { if (confirm) void runAction(confirm); }} /><Button label="Keep booking open" variant="ghost" onPress={() => setConfirm(null)} /></Sheet>
  </View>;
}