import { Bell, Bookmark, CalendarDays, ChevronDown, CircleHelp, Compass, House, LogOut, MapPin, ShieldCheck, UserRound, Wallet, Wrench, type LucideIcon } from 'lucide-react-native';
import { useState, type ReactNode } from 'react';
import { Pressable, View, useWindowDimensions } from 'react-native';
import type { Job } from '../domain/marketplace';
import { useAuth } from '../stores/auth';
import { Avatar, Badge, Button, Copy, Heading, IconButton, Logo, RoleBadge, Sheet } from './ui';

export type Tab = 'home' | 'explore' | 'bookings' | 'saved' | 'earnings' | 'account';
export function Shell({ children, tab, onTab, jobs, onJob, onLocation, location = 'Indiranagar, Bengaluru' }: { children: ReactNode; tab: Tab; onTab: (tab: Tab) => void; jobs: Job[]; onJob: (id: string) => void; onLocation?: () => void; location?: string }) {
  const { width } = useWindowDimensions();
  const desktop = width >= 1050;
  const { profile, mode, logout, loginDemo } = useAuth();
  const [dialog, setDialog] = useState<'notifications' | 'help' | null>(null);
  if (!profile) return null;
  const worker = profile.role === 'worker';
  const items: { id: Tab; label: string; icon: LucideIcon }[] = worker ? [{ id: 'home', label: 'Overview', icon: House }, { id: 'explore', label: 'Job feed', icon: Compass }, { id: 'bookings', label: 'My jobs', icon: CalendarDays }, { id: 'earnings', label: 'Earnings', icon: Wallet }] : [{ id: 'home', label: 'Overview', icon: House }, { id: 'explore', label: 'Find services', icon: Compass }, { id: 'bookings', label: 'My bookings', icon: CalendarDays }, { id: 'saved', label: 'Saved professionals', icon: Bookmark }];
  const activeCount = jobs.filter(job => ['requested', 'accepted', 'in_progress'].includes(job.status)).length;
  return <View className="flex-1 flex-row bg-canvas">
    {desktop && <View className="w-[236px] border-r border-line bg-white px-5 pb-6 pt-9"><View className="px-3"><Logo /><View className="mt-6"><RoleBadge role={profile.role} /></View></View><Copy className="mb-3 mt-10 px-3 font-semibold text-[10px] text-muted">YOUR WORKSPACE</Copy><View className="gap-2">{items.map(({ id, label, icon: Icon }) => <Pressable key={id} accessibilityRole="tab" accessibilityState={{ selected: tab === id }} onPress={() => onTab(id)} className={`min-h-12 flex-row items-center gap-3 rounded-lg px-3 ${tab === id ? 'bg-mint' : ''}`}><Icon size={19} color={tab === id ? '#287454' : '#7A8981'} /><Copy className={`flex-1 text-[13px] ${tab === id ? 'font-bold text-primary' : 'text-muted'}`}>{label}</Copy>{id === 'bookings' && activeCount > 0 && <View className="h-5 min-w-5 items-center justify-center rounded bg-white px-1"><Copy className="font-semibold text-[10px] text-primary">{activeCount}</Copy></View>}</Pressable>)}</View><View className="mt-8 border-t border-line pt-5"><Pressable accessibilityRole="button" onPress={() => onTab('account')} className="min-h-12 flex-row items-center gap-3 px-3"><UserRound size={19} color="#7A8981" /><Copy className="text-[13px] text-muted">My account</Copy></Pressable><Pressable accessibilityRole="button" onPress={() => setDialog('help')} className="min-h-12 flex-row items-center gap-3 px-3"><CircleHelp size={19} color="#7A8981" /><Copy className="text-[13px] text-muted">Help & support</Copy></Pressable></View><View className="flex-1" /><View className="mb-6 gap-3 border-t border-line px-3 pt-5"><View className="h-9 w-9 items-center justify-center rounded-lg bg-peach"><Wrench size={18} color="#A77954" /></View><Copy className="font-display text-[14px]">Local hands.{ '\n' }Lasting connections.</Copy><Copy className="text-[11px] leading-[18px] text-muted">Made for your neighborhood.</Copy>{mode === 'demo' && <Badge label="DEMO WORKSPACE" tone="amber" />}</View><Pressable accessibilityRole="button" onPress={() => void logout()} className="flex-row items-center gap-3 border-t border-line px-2 pt-5"><Avatar name={profile.name} /><View className="flex-1"><Copy className="font-semibold text-xs">{profile.name}</Copy><Copy className="text-[11px] text-muted">Sign out</Copy></View><LogOut size={16} color="#7A8981" /></Pressable></View>}
    <View className="flex-1"><View className="min-h-[88px] flex-row items-center justify-between gap-3 border-b border-line bg-white px-5 md:px-9">{desktop ? <Copy className="text-[13px] text-muted">{worker ? 'Partner workspace' : 'Your neighborhood, connected'}</Copy> : <Logo />}<View className="flex-row items-center gap-2 md:gap-5">{width >= 650 && <Pressable accessibilityRole="button" accessibilityLabel="Update service location" onPress={onLocation} disabled={!onLocation} className="flex-row items-center gap-2"><MapPin size={16} color="#287454" /><View><Copy className="text-[9px] leading-4 text-muted">YOUR NEIGHBORHOOD</Copy><Copy className="font-semibold text-xs">{location}</Copy></View>{onLocation && <ChevronDown size={14} color="#7A8981" />}</Pressable>}<IconButton icon={Bell} label="Notifications" onPress={() => setDialog('notifications')} /><Pressable accessibilityRole="button" accessibilityLabel="My account" onPress={() => onTab('account')}><Avatar name={profile.name} /></Pressable></View></View>
    {children}
    {!desktop && <View className="flex-row border-t border-line bg-white pb-1 pt-2">{items.map(({ id, label, icon: Icon }) => <Pressable key={id} accessibilityRole="tab" accessibilityLabel={label} accessibilityState={{ selected: tab === id }} onPress={() => onTab(id)} className="min-h-14 flex-1 items-center justify-center gap-1"><Icon size={20} color={tab === id ? '#287454' : '#7A8981'} /><Copy numberOfLines={1} className={`text-[10px] ${tab === id ? 'font-bold text-primary' : 'text-muted'}`}>{id === 'saved' ? 'Saved' : label}</Copy></Pressable>)}</View>}
    </View>
    <Sheet visible={dialog !== null} title={dialog === 'notifications' ? 'Your updates' : 'Here for you'} onClose={() => setDialog(null)}>{dialog === 'notifications' ? jobs.length ? jobs.slice(0, 8).map(job => <Pressable accessibilityRole="button" key={job.id} onPress={() => { setDialog(null); onJob(job.id); }} className="gap-1 border-b border-line pb-4"><Copy className="font-semibold">{job.title}</Copy><Copy className="text-xs text-muted">{job.workerName} · {job.status.replace('_', ' ')}</Copy></Pressable>) : <Copy className="text-muted">You&apos;re all caught up.</Copy> : <><Heading className="text-lg">How is my booking protected?</Heading><Copy>Work can only begin after your assigned professional enters your Secure Start Code. Share it in person, when you are ready.</Copy><Heading className="text-lg">What if my plans change?</Heading><Copy>You can cancel from your booking before work starts. For an active job, use the safety controls.</Copy><View className="flex-row items-center gap-2"><ShieldCheck size={18} color="#287454" /><Copy className="text-primary">Emergency assistance: 112</Copy></View>{mode === 'demo' && <Button label={`Switch to demo ${worker ? 'customer' : 'worker'}`} variant="secondary" onPress={() => { setDialog(null); void loginDemo(worker ? 'customer' : 'worker'); }} />}</>}</Sheet>
  </View>;
}